-- ============================================================================
-- VerdeMais — schema baseline para Postgres (Neon)
-- Gerado a partir do estado final das 55 migrations SQLite do D1.
--
-- Decisões de compatibilidade (deliberadas, para não tocar nas ~1.200 queries):
--   * Datas (DATE/DATETIME) permanecem `text` no formato 'YYYY-MM-DD[ HH:MM:SS]'
--     em UTC, como o SQLite gravava. Mantém a ordenação lexical de que o código
--     depende e devolve string no JSON, igual a hoje.
--   * REAL -> double precision (não numeric): o driver pg devolve numeric como
--     STRING, o que quebraria toda a aritmética financeira do app.
--   * BOOLEAN -> integer: o código compara com 0/1 em toda parte.
--   * AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY, para permitir inserir
--     ids explícitos durante a migração de dados do D1.
--   * Foreign keys aplicadas no fim, para não depender da ordem das tabelas.
-- ============================================================================

SET client_min_messages = warning;

-- ── Tabelas ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS alertas_cartao (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     integer NOT NULL,
  cartao_id   integer NOT NULL,
  tipo        text NOT NULL CHECK (tipo IN ('limite_alto','fechamento_proximo','vencimento_proximo','fatura_alta')),
  titulo      text NOT NULL,
  mensagem    text NOT NULL,
  lido        integer DEFAULT 0,
  created_at  text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS amortization_simulations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  financing_id integer,
  original_balance double precision NOT NULL,
  original_installment double precision NOT NULL,
  original_remaining_months integer NOT NULL,
  annual_rate double precision NOT NULL,
  system text NOT NULL CHECK(system IN ('PRICE','SAC','SACRE')),
  amortization_amount double precision NOT NULL,
  new_installment_reduce_payment double precision,
  interest_saved_reduce_payment double precision,
  new_remaining_months_reduce_term integer,
  interest_saved_reduce_term double precision,
  months_saved_reduce_term integer,
  recommended_scenario text CHECK(recommended_scenario IN ('reduce_payment','reduce_term')),
  recommendation_reason text,
  simulation_date text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS analise_compras_fantasma (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  mes integer NOT NULL,
  ano integer NOT NULL,
  total_analisado double precision DEFAULT 0,
  total_impulsivo double precision DEFAULT 0,
  percentual_impulsivo double precision DEFAULT 0,
  updated_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(user_id, mes, ano)
);

CREATE TABLE IF NOT EXISTS antecipacoes (
  id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                 integer NOT NULL,
  descricao               text NOT NULL,
  valor_total             double precision NOT NULL,
  data_vencimento_original text NOT NULL,
  data_antecipacao        text NOT NULL,
  economia_juros          double precision DEFAULT 0,
  status                  text DEFAULT 'pendente'
    CHECK(status IN ('pendente','antecipada','cancelada')),
  tipo                    text DEFAULT 'conta'
    CHECK(tipo IN ('conta','parcela','fatura','fatura_cartao','emprestimo','financiamento')),
  referencia_id           integer,
  referencia_tipo         text,
  observacoes             text,
  created_at              text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  mes_fatura integer,
  ano_fatura integer
);

CREATE TABLE IF NOT EXISTS assinaturas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL UNIQUE,
  plano text NOT NULL DEFAULT 'free' CHECK(plano IN ('free', 'premium', 'pro')),
  status text DEFAULT 'ativo' CHECK(status IN ('ativo', 'inativo', 'cancelado', 'trial')),
  data_inicio text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  data_fim text,
  stripe_customer_id text,
  stripe_subscription_id text
);

CREATE TABLE IF NOT EXISTS assinaturas_canceladas_historico (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  subscription_id integer,
  service_nome text NOT NULL,
  service_type text DEFAULT 'unknown',
  amount double precision NOT NULL,
  frequency_label text DEFAULT 'mensal',
  yearly_cost double precision NOT NULL,
  cancelled_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  meses_desde_cancelamento integer DEFAULT 0,
  economia_acumulada double precision DEFAULT 0,
  economia_anual_projetada double precision DEFAULT 0,
  motivo text,
  notas text
);

CREATE TABLE IF NOT EXISTS assistente_conversas (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     integer NOT NULL,
  mensagem    text NOT NULL,
  resposta    text NOT NULL,
  intencao    text,
  created_at  text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS budget_rule_config (
  user_id integer PRIMARY KEY,
  needs_pct integer DEFAULT 50,
  wants_pct integer DEFAULT 30,
  savings_pct integer DEFAULT 20,
  custom_name text DEFAULT 'Regra 50/30/20',
  created_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  updated_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS card_category_limits (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id     integer NOT NULL,
  user_id     integer NOT NULL,
  categoria   text NOT NULL,
  limite_mensal double precision NOT NULL CHECK(limite_mensal > 0),
  created_at  text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(card_id, categoria)
);

CREATE TABLE IF NOT EXISTS card_charges (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id          integer NOT NULL,
  expense_id       integer,
  descricao        text    NOT NULL,
  valor            double precision    NOT NULL CHECK (valor > 0),
  data_compra      text    NOT NULL,
  data_vencimento  text    NOT NULL,
  billing_month    integer NOT NULL CHECK (billing_month BETWEEN 1 AND 12),
  billing_year     integer NOT NULL CHECK (billing_year  >= 2024),
  parcela_atual    integer,
  total_parcelas   integer,
  purchase_group_id text,
  status           text    NOT NULL DEFAULT 'pendente'
                          CHECK (status IN ('pendente','pago','cancelado')),
  created_at       text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS card_contestacoes (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  charge_id   integer NOT NULL,
  user_id     integer NOT NULL,
  motivo      text NOT NULL,
  status      text NOT NULL DEFAULT 'aberta' CHECK(status IN ('aberta','em_analise','resolvida','recusada')),
  observacao  text,
  created_at  text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  updated_at  text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS cartoes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  nome text NOT NULL,
  bandeira text NOT NULL CHECK(bandeira IN ('visa', 'mastercard', 'elo', 'amex', 'hipercard', 'outros')),
  banco text NOT NULL,
  limite_total double precision NOT NULL DEFAULT 0,
  limite_disponivel double precision DEFAULT 0,
  dia_vencimento integer NOT NULL,
  dia_fechamento integer NOT NULL,
  cor text DEFAULT '#2FBF71',
  ativo integer DEFAULT 1,
  ultimos_digitos text,
  data_criacao text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  apelido text DEFAULT NULL,
  tipo_cartao text NOT NULL DEFAULT 'PF' CHECK(tipo_cartao IN ('PF','PJ'))
);

CREATE TABLE IF NOT EXISTS cdi_historico (
  data        text PRIMARY KEY,
  taxa        double precision NOT NULL,
  created_at  text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS chat_messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  sender text CHECK(sender IN ('user', 'bot')) NOT NULL,
  message text NOT NULL,
  intent text,
  created_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS compras_recorrentes_detectadas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  normalized_description text NOT NULL,
  original_description text NOT NULL,
  categoria text,
  amount_avg double precision NOT NULL,
  amount_min double precision,
  amount_max double precision,
  frequency_label text DEFAULT 'mensal',
  occurrences integer DEFAULT 0,
  first_occurrence text,
  last_occurrence text,
  average_interval_days double precision,
  confidence double precision DEFAULT 0,
  ia_classificado integer DEFAULT 0,
  ia_tipo text,
  status text DEFAULT 'active' CHECK(status IN ('active','reduced','cancelled','ignored')),
  valor_reduzido double precision,
  economia_mensal double precision DEFAULT 0,
  economia_anual double precision DEFAULT 0,
  reduced_at text,
  created_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  updated_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(user_id, normalized_description)
);

CREATE TABLE IF NOT EXISTS conquistas_definicoes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo text UNIQUE NOT NULL,
  titulo text NOT NULL,
  descricao text NOT NULL,
  icone text DEFAULT '🏆',
  categoria text DEFAULT 'geral',
  plano_requerido text DEFAULT 'free',
  pontos integer DEFAULT 10,
  raridade text DEFAULT 'comum' CHECK(raridade IN ('comum', 'raro', 'epico', 'lendario'))
);

CREATE TABLE IF NOT EXISTS conquistas_usuario (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  conquista_codigo text NOT NULL,
  data_conquista text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  visualizado integer DEFAULT 0,
  UNIQUE(user_id, conquista_codigo)
);

CREATE TABLE IF NOT EXISTS cotacoes_cache (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo        text NOT NULL,
  symbol      text NOT NULL,
  valor_brl   double precision,
  valor_usd   double precision,
  variacao_24h double precision,
  dados_json  text,
  atualizado_em text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(tipo, symbol)
);

CREATE TABLE IF NOT EXISTS csv_templates (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     integer NOT NULL,
  nome        text NOT NULL,
  banco       text NOT NULL,
  col_data    text NOT NULL DEFAULT 'data',
  col_desc    text NOT NULL DEFAULT 'descricao',
  col_valor   text NOT NULL DEFAULT 'valor',
  col_tipo    text,
  separador   text NOT NULL DEFAULT ';',
  decimal_sep text NOT NULL DEFAULT ',',
  skip_rows   integer DEFAULT 1,
  filtro_tipo text,
  ativo       integer DEFAULT 1,
  created_at  text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(user_id, banco)
);

CREATE TABLE IF NOT EXISTS desafio_config (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         integer NOT NULL UNIQUE,
  year            integer NOT NULL DEFAULT 2026,
  valor_base      double precision    NOT NULL DEFAULT 1.0,
  multiplicador   double precision    NOT NULL DEFAULT 1.0,
  modo_invertido  integer NOT NULL DEFAULT 0,
  meta_vinculada  integer,
  created_at      text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  updated_at      text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  investimento_vinculado integer
);

CREATE TABLE IF NOT EXISTS despesa_tags (
  despesa_id  integer NOT NULL,
  tag_id      integer NOT NULL,
  PRIMARY KEY (despesa_id, tag_id)
);

CREATE TABLE IF NOT EXISTS despesas (
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             integer NOT NULL,
  descricao           text    NOT NULL,
  data                text    NOT NULL,
  categoria           text    NOT NULL,
  subcategoria        text,
  valor               double precision    NOT NULL,
  parcelado           integer DEFAULT 0,
  numero_parcelas     integer DEFAULT 1,
  parcela_atual       integer DEFAULT 1,
  status              text    DEFAULT 'pendente' CHECK(status IN ('pago','pendente','cancelado')),
  fixa_ou_variavel    text    DEFAULT 'variavel' CHECK(fixa_ou_variavel IN ('fixa','variavel')),
  recorrente          integer DEFAULT 0,
  vencimento          text,
  observacoes         text,
  data_criacao        text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  cartao_id           integer,
  meio_pagamento      text    DEFAULT 'dinheiro' CHECK(meio_pagamento IN (
                        'dinheiro','pix','cartao_credito','cartao_debito',
                        'parcelado_cartao','transferencia','boleto','outros',
                        'debito','parcelado_sem_juros'
                      )),
  billing_month       integer CHECK(billing_month BETWEEN 1 AND 12),
  billing_year        integer CHECK(billing_year >= 2024),
  purchase_group_id   text,
  tipo                text    DEFAULT 'normal',
  eh_aporte_patrimonial integer DEFAULT 0,
  recorrencia_id integer,
  data_pagamento text
);

CREATE TABLE IF NOT EXISTS detected_subscriptions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  normalized_description text NOT NULL,
  original_description text NOT NULL,
  amount double precision NOT NULL,
  frequency integer NOT NULL,
  first_occurrence text NOT NULL,
  last_occurrence text NOT NULL,
  average_interval_days double precision,
  confidence double precision NOT NULL,
  service_type text DEFAULT 'unknown',
  yearly_cost double precision NOT NULL,
  status text DEFAULT 'detected' CHECK(status IN ('detected','confirmed','cancelled','ignored')),
  user_feedback text CHECK(user_feedback IN ('use_regularly','want_cancel','ignore','reduced_plan')),
  detected_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  updated_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  service_nome text DEFAULT '',
  frequency_label text DEFAULT 'mensal',
  ai_enhanced integer DEFAULT 0,
  ai_analysis text,
  valor_antigo double precision,
  reduced_at text,
  recorrencia_id integer,
  economia_acumulada_reducao double precision DEFAULT 0
);

CREATE TABLE IF NOT EXISTS email_verifications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer,
  email text NOT NULL,
  code text NOT NULL,
  attempts integer DEFAULT 0,
  expires_at text NOT NULL,
  verified_at text NULL,
  created_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS emprestimos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  descricao text NOT NULL,
  tipo text DEFAULT 'pessoal' CHECK(tipo IN ('pessoal', 'consignado', 'veiculo', 'estudantil', 'microempresa', 'amigos_familia', 'imovel', 'imovel_comercial', 'rural', 'outros')),
  valor_original double precision NOT NULL,
  valor_pago double precision DEFAULT 0,
  saldo_devedor double precision NOT NULL,
  taxa_juros_mensal double precision NOT NULL,
  taxa_juros_anual double precision NOT NULL,
  numero_parcelas integer NOT NULL,
  parcelas_pagas integer DEFAULT 0,
  valor_parcela double precision NOT NULL,
  data_inicio text NOT NULL,
  data_previsao_fim text,
  dia_vencimento integer,
  credor text,
  status text DEFAULT 'ativo' CHECK(status IN ('ativo', 'quitado', 'em_atraso', 'negociado')),
  observacoes text,
  data_criacao text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  data_primeira_parcela text,
  parcelas_restantes integer GENERATED ALWAYS AS (numero_parcelas - parcelas_pagas) STORED,
  proximo_vencimento text
);

CREATE TABLE IF NOT EXISTS financiamento_entrada_parcelas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  financiamento_id integer NOT NULL,
  numero integer NOT NULL,
  valor double precision NOT NULL,
  vencimento text NOT NULL,
  status text DEFAULT 'pendente' CHECK(status IN ('pendente','pago','atrasado')),
  data_pagamento text,
  observacoes text,
  criado_em text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS financiamentos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  descricao text NOT NULL,
  tipo_imovel text DEFAULT 'residencial'
    CHECK(tipo_imovel IN ('residencial','comercial','terreno','rural','veiculo','outros')),
  valor_imovel double precision NOT NULL,
  valor_financiado double precision NOT NULL,
  valor_entrada double precision DEFAULT 0,
  taxa_juros_anual double precision NOT NULL,
  taxa_juros_mensal double precision NOT NULL,
  numero_parcelas integer NOT NULL,
  parcelas_pagas integer DEFAULT 0,
  valor_parcela double precision NOT NULL,
  saldo_devedor double precision NOT NULL,
  data_inicio text NOT NULL,
  data_previsao_fim text,
  sistema_amortizacao text DEFAULT 'price'
    CHECK(sistema_amortizacao IN ('price','sac','sacre')),
  banco text,
  contrato text,
  indexador text DEFAULT 'prefixado'
    CHECK(indexador IN ('prefixado','ipca','igpm','tr','cdi')),
  status text DEFAULT 'ativo'
    CHECK(status IN ('ativo','quitado','em_atraso')),
  observacoes text,
  data_criacao text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  entrada_parcelada integer DEFAULT 0,
  entrada_num_parcelas integer DEFAULT 0,
  entrada_parcelas_pagas integer DEFAULT 0,
  entrada_valor_parcela double precision DEFAULT 0,
  evolucao_obra_pct double precision DEFAULT 0,
  tipo_financiamento text DEFAULT 'pronto'
    CHECK(tipo_financiamento IN ('pronto','planta','construcao','terreno','reforma','veiculo','outros')),
  tipo_bem text DEFAULT 'imovel',
  parcelas_restantes integer GENERATED ALWAYS AS (numero_parcelas - parcelas_pagas) STORED,
  proximo_vencimento text,
  seguro_mip double precision DEFAULT 0,
  seguro_dfi double precision DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ia_analise_cache (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  tipo text NOT NULL,
  input_hash text NOT NULL,
  resultado text NOT NULL,
  created_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(user_id, tipo, input_hash)
);

CREATE TABLE IF NOT EXISTS ia_insights (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  tipo text NOT NULL,
  titulo text NOT NULL,
  conteudo text NOT NULL,
  prioridade text DEFAULT 'media' CHECK(prioridade IN ('alta', 'media', 'baixa')),
  categoria text DEFAULT 'geral',
  lido integer DEFAULT 0,
  data_criacao text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  valido_ate text
);

CREATE TABLE IF NOT EXISTS importacao_log (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      integer NOT NULL,
  hash         text NOT NULL,
  data_transacao text NOT NULL,
  descricao    text NOT NULL,
  valor        DECIMAL(10,2) NOT NULL,
  importado_em text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(user_id, hash)
);

CREATE TABLE IF NOT EXISTS investimento_tags (
  investimento_id integer NOT NULL,
  tag_id          integer NOT NULL,
  PRIMARY KEY (investimento_id, tag_id)
);

CREATE TABLE IF NOT EXISTS investimentos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  nome text NOT NULL,
  tipo text NOT NULL CHECK(tipo IN ('tesouro_direto','cdb','lci','lca','acoes','fii','cripto','poupanca','caixinha','outros')),
  valor_investido double precision NOT NULL,
  rentabilidade_percentual double precision DEFAULT 0,
  valor_atual double precision DEFAULT 0,
  risco text DEFAULT 'baixo' CHECK(risco IN ('baixo','medio','alto')),
  data_inicio text NOT NULL,
  data_vencimento text,
  instituicao text,
  observacoes text,
  percentual_cdi double precision DEFAULT NULL,
  cdi_atual double precision DEFAULT 13.65,
  data_ultimo_calculo text DEFAULT NULL,
  data_criacao text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  registra_saida_saldo integer DEFAULT 1,
  meta_valor double precision DEFAULT NULL,
  tags text DEFAULT NULL,
  symbol text DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS lembretes (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              integer NOT NULL,
  titulo               text NOT NULL,
  descricao            text,
  tipo                 text DEFAULT 'conta',
  valor_estimado       double precision DEFAULT 0,
  dia_vencimento       integer,
  frequencia           text DEFAULT 'mensal',
  ativo                integer DEFAULT 1,
  ultimo_recebimento   text,
  proximo_vencimento   text,
  status_mes           text DEFAULT 'aguardando',
  alertar_dias_antes   integer DEFAULT 3,
  data_criacao         text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  notas                text,
  tags                 text,
  cor text DEFAULT '#2FBF71'
);

CREATE TABLE IF NOT EXISTS lembretes_historico (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lembrete_id integer NOT NULL,
  user_id integer NOT NULL,
  data_referencia text NOT NULL,
  status text NOT NULL CHECK(status IN ('recebido', 'pago', 'ignorado')),
  valor_real double precision DEFAULT 0,
  observacoes text,
  data_registro text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS meta_historico (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meta_id      integer NOT NULL,
  user_id      integer NOT NULL,
  tipo         text NOT NULL CHECK(tipo IN ('aporte','saque','ajuste')),
  valor        double precision NOT NULL,
  descricao    text,
  valor_antes  double precision NOT NULL,
  valor_depois double precision NOT NULL,
  data         text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS meta_tags (
  meta_id integer NOT NULL,
  tag_id  integer NOT NULL,
  PRIMARY KEY (meta_id, tag_id)
);

CREATE TABLE IF NOT EXISTS metas (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              integer NOT NULL,
  nome                 text NOT NULL,
  descricao            text,
  valor_objetivo       double precision NOT NULL,
  valor_atual          double precision DEFAULT 0,
  data_meta            text NOT NULL,
  categoria            text DEFAULT 'economia',
  cor                  text DEFAULT '#2FBF71',
  icone                text DEFAULT 'piggy-bank',
  status               text DEFAULT 'ativa'
                       CHECK(status IN ('ativa', 'concluida', 'cancelada', 'arquivada')),
  data_criacao         text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  linked_debt_type     text
                       CHECK (linked_debt_type IN ('all','financiamento','emprestimo','especifico')),
  linked_debt_id       integer,
  original_debt_amount double precision,
  prioridade           integer DEFAULT 2 CHECK(prioridade IN (1,2,3)),
  milestones_disparados text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS orcamento_global (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       integer NOT NULL,
  mes           integer NOT NULL CHECK(mes BETWEEN 1 AND 12),
  ano           integer NOT NULL CHECK(ano >= 2024),
  limite_global DECIMAL(10,2) NOT NULL CHECK(limite_global > 0),
  rollover      integer DEFAULT 0,
  created_at    text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  updated_at    text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(user_id, mes, ano)
);

CREATE TABLE IF NOT EXISTS orcamento_rollover (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        integer NOT NULL,
  categoria      text NOT NULL,
  mes_origem     integer NOT NULL,
  ano_origem     integer NOT NULL,
  mes_destino    integer NOT NULL,
  ano_destino    integer NOT NULL,
  saldo_rollover DECIMAL(10,2) NOT NULL,
  created_at     text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(user_id, categoria, mes_destino, ano_destino)
);

CREATE TABLE IF NOT EXISTS orcamentos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  categoria text NOT NULL,
  mes integer NOT NULL CHECK (mes BETWEEN 1 AND 12),
  ano integer NOT NULL CHECK (ano >= 2024),
  limite DECIMAL(10,2) NOT NULL CHECK (limite > 0),
  alerta_percentual integer DEFAULT 80 CHECK (alerta_percentual BETWEEN 50 AND 100),
  created_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  updated_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  notas text,
  alerta_disparado integer DEFAULT 0,
  alerta_70_disparado  integer DEFAULT 0,
  alerta_90_disparado  integer DEFAULT 0,
  alerta_100_disparado integer DEFAULT 0,
  UNIQUE(user_id, categoria, mes, ano)
);

CREATE TABLE IF NOT EXISTS pagamentos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  asaas_subscription_id text,
  asaas_customer_id text,
  asaas_payment_id text,
  plano text NOT NULL CHECK (plano IN ('premium', 'pro')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'cancelled', 'expired', 'overdue')),
  forma_pagamento text CHECK (forma_pagamento IN ('PIX', 'BOLETO', 'CREDIT_CARD')),
  valor DECIMAL(10,2) NOT NULL,
  checkout_url text,
  boleto_url text,
  pix_qrcode text,
  pix_copia_cola text,
  ativado_em text NULL,
  expira_em text NULL,
  created_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  updated_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS patrimonio_historico (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  mes text NOT NULL,
  total_investimentos double precision DEFAULT 0,
  total_reservas double precision DEFAULT 0,
  total_dividas double precision DEFAULT 0,
  patrimonio_liquido double precision DEFAULT 0,
  criado_em text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(user_id, mes)
);

CREATE TABLE IF NOT EXISTS recebimentos_parcelados (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  descricao text NOT NULL,
  valor_total double precision NOT NULL,
  numero_parcelas integer NOT NULL DEFAULT 1,
  valor_parcela double precision NOT NULL,
  data_inicio text NOT NULL,
  data_fim text,
  tipo text DEFAULT 'venda' CHECK(tipo IN ('venda','servico','aluguel','emprestimo_a_receber','contrato','outros')),
  pagador text,
  status text DEFAULT 'ativo' CHECK(status IN ('ativo','concluido','cancelado','em_atraso')),
  observacoes text,
  created_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS recebimentos_parcelas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recebimento_id integer NOT NULL,
  user_id integer NOT NULL,
  numero_parcela integer NOT NULL,
  valor double precision NOT NULL,
  data_prevista text NOT NULL,
  data_recebimento text,
  status text DEFAULT 'pendente' CHECK(status IN ('pendente','recebida','em_atraso','cancelada')),
  observacoes text,
  receita_id integer
);

CREATE TABLE IF NOT EXISTS receita_tags (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receita_id integer NOT NULL,
  tag_id     integer NOT NULL,
  UNIQUE(receita_id, tag_id)
);

CREATE TABLE IF NOT EXISTS receitas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  descricao text NOT NULL,
  data text NOT NULL,
  categoria text NOT NULL,
  valor double precision NOT NULL,
  recorrente integer DEFAULT 0,
  frequencia text DEFAULT NULL,
  observacoes text,
  data_criacao text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  recorrencia_id integer,
  meio_pagamento text,
  tipo text DEFAULT 'receita'
);

CREATE TABLE IF NOT EXISTS recorrencias (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        integer NOT NULL,
  tipo           text NOT NULL CHECK (tipo IN ('despesa', 'receita')),
  descricao      text NOT NULL,
  valor          DECIMAL(10,2) NOT NULL DEFAULT 0,
  categoria      text NOT NULL,
  dia_vencimento integer NOT NULL CHECK (dia_vencimento BETWEEN 1 AND 31),
  meio_pagamento text DEFAULT 'outros',
  ativa          integer DEFAULT 1,
  data_inicio    text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD'),
  data_fim       text NULL,
  ultimo_gerado  text NULL,
  ultimo_valor   DECIMAL(10,2) NULL,
  valor_variavel integer DEFAULT 0,
  total_gerado   integer DEFAULT 0,
  created_at     text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  notas text,
  tags text
);

CREATE TABLE IF NOT EXISTS recorrencias_historico (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recorrencia_id integer NOT NULL,
  user_id       integer NOT NULL,
  mes           integer NOT NULL,
  ano           integer NOT NULL,
  valor         DECIMAL(10,2) NOT NULL,
  observacao    text NULL,
  lancado_em    text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(recorrencia_id, mes, ano)
);

CREATE TABLE IF NOT EXISTS regra_config (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           integer NOT NULL UNIQUE,
  pct_necessidades  integer NOT NULL DEFAULT 50,
  pct_desejos       integer NOT NULL DEFAULT 30,
  pct_poupanca      integer NOT NULL DEFAULT 20,
  categorias_necessidades text DEFAULT NULL,
  categorias_desejos      text DEFAULT NULL,
  categorias_poupanca     text DEFAULT NULL,
  created_at        text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  updated_at        text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  nome_personalizado text DEFAULT 'Regra 50/30/20'
);

CREATE TABLE IF NOT EXISTS reserva_emergencia (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  nome text NOT NULL DEFAULT 'Reserva de Emergência',
  objetivo_meses integer NOT NULL DEFAULT 6,
  valor_atual double precision NOT NULL DEFAULT 0,
  data_atualizacao text,
  observacoes text,
  data_criacao text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  banco text DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS reserva_historico (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id     integer NOT NULL,
  user_id        integer NOT NULL,
  tipo           text NOT NULL CHECK(tipo IN ('deposito','saque','ajuste')),
  valor          double precision NOT NULL,
  descricao      text,
  saldo_antes    double precision NOT NULL DEFAULT 0,
  saldo_depois   double precision NOT NULL DEFAULT 0,
  data           text NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD'),
  criado_em      text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS reserva_tags (
  reserva_id integer NOT NULL,
  tag_id     integer NOT NULL,
  PRIMARY KEY (reserva_id, tag_id)
);

CREATE TABLE IF NOT EXISTS reserve_transactions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserve_id integer NOT NULL,
  type text NOT NULL CHECK(type IN ('deposit','withdrawal')),
  amount double precision NOT NULL CHECK(amount > 0),
  description text,
  date text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS score_historico (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  mes text NOT NULL,
  score_geral integer NOT NULL,
  score_fluxo integer,
  score_reserva integer,
  score_dividas integer,
  score_investimentos integer,
  score_metas integer,
  criado_em text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(user_id, mes)
);

CREATE TABLE IF NOT EXISTS sessions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  token text UNIQUE NOT NULL,
  expires_at text NOT NULL,
  created_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS shared_expenses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_id integer NOT NULL,
  user_id integer NOT NULL,
  partner_name text NOT NULL,
  partner_email text,
  user_percentage double precision DEFAULT 50.0 CHECK(user_percentage BETWEEN 0 AND 100),
  partner_percentage double precision DEFAULT 50.0,
  status text DEFAULT 'pending' CHECK(status IN ('pending','settled')),
  created_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS specialized_reserves (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  type text NOT NULL DEFAULT 'custom' CHECK(type IN (
    'emergency','travel','health','unemployment',
    'family','education','vehicle','event','custom'
  )),
  name text NOT NULL,
  description text,
  target_amount double precision NOT NULL CHECK(target_amount > 0),
  current_amount double precision DEFAULT 0 CHECK(current_amount >= 0),
  priority integer DEFAULT 3 CHECK(priority BETWEEN 1 AND 5),
  deadline text,
  icon text DEFAULT '🎯',
  color text DEFAULT '#10B981',
  monthly_target double precision,
  status text DEFAULT 'active' CHECK(status IN ('active','paused','completed','cancelled')),
  created_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  completed_at text,
  linked_meta_id integer
);

CREATE TABLE IF NOT EXISTS tags (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     integer NOT NULL,
  nome        text NOT NULL,
  cor         text DEFAULT '#10B981',
  created_at  text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(user_id, nome)
);

CREATE TABLE IF NOT EXISTS tags_auto_config (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     integer NOT NULL,
  modulo      text NOT NULL,
  ativo       integer DEFAULT 1,
  created_at  text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(user_id, modulo)
);

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  email text UNIQUE NOT NULL,
  senha text NOT NULL,
  plano text DEFAULT 'free' CHECK(plano IN ('free', 'premium', 'pro')),
  perfil_investidor text DEFAULT 'moderado' CHECK(perfil_investidor IN ('conservador', 'moderado', 'arrojado')),
  avatar_color text DEFAULT '#2FBF71',
  data_criacao text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  ultimo_acesso text,
  profissao text,
  situacao_emprego text DEFAULT 'empregado',
  salario_mensal double precision DEFAULT 0,
  outras_rendas double precision DEFAULT 0,
  dependentes integer DEFAULT 0,
  estado_civil text DEFAULT 'solteiro',
  cidade text,
  estado text,
  perfil_completo integer DEFAULT 0,
  onboarding_step integer DEFAULT 0,
  cpf text,
  telefone text,
  score_saude integer DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS weekly_challenge_config (
  user_id integer PRIMARY KEY,
  start_amount DECIMAL(10,2) DEFAULT 1.00,
  increment_amount DECIMAL(10,2) DEFAULT 1.00,
  mode text DEFAULT 'standard',
  currency text DEFAULT 'BRL',
  created_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  updated_at text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS weekly_challenges (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  year integer NOT NULL,
  week_number integer NOT NULL CHECK(week_number BETWEEN 1 AND 52),
  target_amount double precision NOT NULL,
  status text DEFAULT 'pending' CHECK(status IN ('pending','completed','skipped')),
  completed_at text,
  config_id integer,
  UNIQUE(user_id, year, week_number)
);

-- ── Foreign keys ─────────────────────────────────────────────────────────

ALTER TABLE alertas_cartao ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE alertas_cartao ADD FOREIGN KEY (cartao_id) REFERENCES cartoes(id) ON DELETE CASCADE;
ALTER TABLE amortization_simulations ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE amortization_simulations ADD FOREIGN KEY (financing_id) REFERENCES financiamentos(id) ON DELETE SET NULL;
ALTER TABLE analise_compras_fantasma ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE antecipacoes ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE assinaturas ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE assinaturas_canceladas_historico ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE assinaturas_canceladas_historico ADD FOREIGN KEY (subscription_id) REFERENCES detected_subscriptions(id) ON DELETE SET NULL;
ALTER TABLE assistente_conversas ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE budget_rule_config ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE card_category_limits ADD FOREIGN KEY (card_id) REFERENCES cartoes(id) ON DELETE CASCADE;
ALTER TABLE card_category_limits ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE card_charges ADD FOREIGN KEY (card_id) REFERENCES cartoes(id)  ON DELETE CASCADE;
ALTER TABLE card_charges ADD FOREIGN KEY (expense_id) REFERENCES despesas(id) ON DELETE SET NULL;
ALTER TABLE card_contestacoes ADD FOREIGN KEY (charge_id) REFERENCES card_charges(id) ON DELETE CASCADE;
ALTER TABLE card_contestacoes ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE cartoes ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE chat_messages ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE compras_recorrentes_detectadas ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE conquistas_usuario ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE desafio_config ADD FOREIGN KEY (investimento_vinculado) REFERENCES investimentos(id);
ALTER TABLE desafio_config ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE desafio_config ADD FOREIGN KEY (meta_vinculada) REFERENCES metas(id) ON DELETE SET NULL;
ALTER TABLE despesa_tags ADD FOREIGN KEY (despesa_id) REFERENCES despesas(id) ON DELETE CASCADE;
ALTER TABLE despesa_tags ADD FOREIGN KEY (tag_id) REFERENCES tags(id)     ON DELETE CASCADE;
ALTER TABLE despesas ADD FOREIGN KEY (cartao_id) REFERENCES cartoes(id);
ALTER TABLE despesas ADD FOREIGN KEY (recorrencia_id) REFERENCES recorrencias(id) ON DELETE SET NULL;
ALTER TABLE despesas ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE detected_subscriptions ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE detected_subscriptions ADD FOREIGN KEY (recorrencia_id) REFERENCES recorrencias(id) ON DELETE SET NULL;
ALTER TABLE email_verifications ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE emprestimos ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE financiamento_entrada_parcelas ADD FOREIGN KEY (financiamento_id) REFERENCES financiamentos(id) ON DELETE CASCADE;
ALTER TABLE financiamentos ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE ia_analise_cache ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE ia_insights ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE importacao_log ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE investimento_tags ADD FOREIGN KEY (investimento_id) REFERENCES investimentos(id) ON DELETE CASCADE;
ALTER TABLE investimento_tags ADD FOREIGN KEY (tag_id) REFERENCES tags(id)          ON DELETE CASCADE;
ALTER TABLE investimentos ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE lembretes ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE lembretes_historico ADD FOREIGN KEY (lembrete_id) REFERENCES lembretes(id) ON DELETE CASCADE;
ALTER TABLE lembretes_historico ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE meta_historico ADD FOREIGN KEY (meta_id) REFERENCES metas(id) ON DELETE CASCADE;
ALTER TABLE meta_historico ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE meta_tags ADD FOREIGN KEY (meta_id) REFERENCES metas(id) ON DELETE CASCADE;
ALTER TABLE meta_tags ADD FOREIGN KEY (tag_id) REFERENCES tags(id)  ON DELETE CASCADE;
ALTER TABLE metas ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE orcamento_global ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE orcamento_rollover ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE orcamentos ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE pagamentos ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE recebimentos_parcelados ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE recebimentos_parcelas ADD FOREIGN KEY (recebimento_id) REFERENCES recebimentos_parcelados(id) ON DELETE CASCADE;
ALTER TABLE recebimentos_parcelas ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE recebimentos_parcelas ADD FOREIGN KEY (receita_id) REFERENCES receitas(id) ON DELETE SET NULL;
ALTER TABLE receita_tags ADD FOREIGN KEY (receita_id) REFERENCES receitas(id)  ON DELETE CASCADE;
ALTER TABLE receita_tags ADD FOREIGN KEY (tag_id)     REFERENCES tags(id)       ON DELETE CASCADE;
ALTER TABLE receitas ADD FOREIGN KEY (recorrencia_id) REFERENCES recorrencias(id) ON DELETE SET NULL;
ALTER TABLE receitas ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE recorrencias ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE recorrencias_historico ADD FOREIGN KEY (recorrencia_id) REFERENCES recorrencias(id) ON DELETE CASCADE;
ALTER TABLE recorrencias_historico ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE regra_config ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE reserva_emergencia ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE reserva_historico ADD FOREIGN KEY (reserva_id) REFERENCES reserva_emergencia(id);
ALTER TABLE reserva_historico ADD FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE reserva_tags ADD FOREIGN KEY (reserva_id) REFERENCES specialized_reserves(id) ON DELETE CASCADE;
ALTER TABLE reserva_tags ADD FOREIGN KEY (tag_id) REFERENCES tags(id)                  ON DELETE CASCADE;
ALTER TABLE reserve_transactions ADD FOREIGN KEY (reserve_id) REFERENCES specialized_reserves(id) ON DELETE CASCADE;
ALTER TABLE sessions ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE shared_expenses ADD FOREIGN KEY (expense_id) REFERENCES despesas(id) ON DELETE CASCADE;
ALTER TABLE shared_expenses ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE specialized_reserves ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE specialized_reserves ADD FOREIGN KEY (linked_meta_id) REFERENCES metas(id) ON DELETE SET NULL;
ALTER TABLE tags ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE tags_auto_config ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE weekly_challenge_config ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE weekly_challenges ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE weekly_challenges ADD FOREIGN KEY (config_id) REFERENCES desafio_config(id);

-- ── Índices ──────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_alertas_cartao ON alertas_cartao (cartao_id);
CREATE INDEX IF NOT EXISTS idx_alertas_user ON alertas_cartao (user_id, lido);
CREATE INDEX IF NOT EXISTS idx_antecipacoes_tipo ON antecipacoes (user_id, tipo);
CREATE INDEX IF NOT EXISTS idx_antecipacoes_user ON antecipacoes (user_id, status);
CREATE INDEX IF NOT EXISTS idx_assinaturas_canceladas_user ON assinaturas_canceladas_historico (user_id, cancelled_at);
CREATE INDEX IF NOT EXISTS idx_assistente_conv_user ON assistente_conversas (user_id);
CREATE INDEX IF NOT EXISTS idx_assistente_conversas_user ON assistente_conversas (user_id);
CREATE INDEX IF NOT EXISTS idx_assistente_user ON assistente_conversas (user_id);
CREATE INDEX IF NOT EXISTS idx_budget_rule_config_user ON budget_rule_config (user_id);
CREATE INDEX IF NOT EXISTS idx_card_charges_billing ON card_charges (card_id, billing_month, billing_year);
CREATE INDEX IF NOT EXISTS idx_card_charges_expense ON card_charges (expense_id);
CREATE INDEX IF NOT EXISTS idx_card_charges_group ON card_charges (purchase_group_id);
CREATE INDEX IF NOT EXISTS idx_cartoes_user_id ON cartoes (user_id);
CREATE INDEX IF NOT EXISTS idx_ccl_card ON card_category_limits (card_id);
CREATE INDEX IF NOT EXISTS idx_ccl_user ON card_category_limits (user_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_user_id ON chat_messages (user_id);
CREATE INDEX IF NOT EXISTS idx_compras_fantasma_user ON analise_compras_fantasma (user_id, ano, mes);
CREATE INDEX IF NOT EXISTS idx_compras_recorrentes_user ON compras_recorrentes_detectadas (user_id, status);
CREATE INDEX IF NOT EXISTS idx_conquistas_user ON conquistas_usuario (user_id);
CREATE INDEX IF NOT EXISTS idx_contest_charge ON card_contestacoes (charge_id);
CREATE INDEX IF NOT EXISTS idx_contest_user ON card_contestacoes (user_id);
CREATE INDEX IF NOT EXISTS idx_csv_templates_user ON csv_templates (user_id);
CREATE INDEX IF NOT EXISTS idx_desafio_config_user ON desafio_config (user_id);
CREATE INDEX IF NOT EXISTS idx_despesa_tags ON despesa_tags (despesa_id);
CREATE INDEX IF NOT EXISTS idx_despesas_cartao_id ON despesas (cartao_id);
CREATE INDEX IF NOT EXISTS idx_despesas_data ON despesas (data);
CREATE INDEX IF NOT EXISTS idx_despesas_recorrencia_id ON despesas (recorrencia_id);
CREATE INDEX IF NOT EXISTS idx_despesas_user_id ON despesas (user_id);
CREATE INDEX IF NOT EXISTS idx_detected_subs_reduced ON detected_subscriptions (user_id, user_feedback) WHERE user_feedback = 'reduced_plan';
CREATE INDEX IF NOT EXISTS idx_detected_subs_status ON detected_subscriptions (user_id, status);
CREATE INDEX IF NOT EXISTS idx_detected_subs_user ON detected_subscriptions (user_id);
CREATE INDEX IF NOT EXISTS idx_emprestimos_status ON emprestimos (status);
CREATE INDEX IF NOT EXISTS idx_emprestimos_user_id ON emprestimos (user_id);
CREATE INDEX IF NOT EXISTS idx_ev_email ON email_verifications (email);
CREATE INDEX IF NOT EXISTS idx_ev_user ON email_verifications (user_id);
CREATE INDEX IF NOT EXISTS idx_ia_insights_user ON ia_insights (user_id);
CREATE INDEX IF NOT EXISTS idx_importacao_log_user ON importacao_log (user_id, hash);
CREATE INDEX IF NOT EXISTS idx_investimento_tags_inv ON investimento_tags (investimento_id);
CREATE INDEX IF NOT EXISTS idx_investimento_tags_tag ON investimento_tags (tag_id);
CREATE INDEX IF NOT EXISTS idx_investimentos_user_id ON investimentos (user_id);
CREATE INDEX IF NOT EXISTS idx_lembretes_user ON lembretes (user_id, ativo);
CREATE INDEX IF NOT EXISTS idx_meta_historico_meta ON meta_historico (meta_id);
CREATE INDEX IF NOT EXISTS idx_meta_historico_user ON meta_historico (user_id, data);
CREATE INDEX IF NOT EXISTS idx_meta_tags_meta ON meta_tags (meta_id);
CREATE INDEX IF NOT EXISTS idx_meta_tags_tag ON meta_tags (tag_id);
CREATE INDEX IF NOT EXISTS idx_orc_global_user ON orcamento_global (user_id, mes, ano);
CREATE INDEX IF NOT EXISTS idx_orc_rollover_user ON orcamento_rollover (user_id, mes_destino, ano_destino);
CREATE INDEX IF NOT EXISTS idx_orcamentos_user_mes ON orcamentos (user_id, mes, ano);
CREATE INDEX IF NOT EXISTS idx_pagamentos_asaas ON pagamentos (asaas_subscription_id);
CREATE INDEX IF NOT EXISTS idx_pagamentos_user ON pagamentos (user_id, status);
CREATE INDEX IF NOT EXISTS idx_patrimonio_historico_user ON patrimonio_historico (user_id, mes DESC);
CREATE INDEX IF NOT EXISTS idx_rec_hist_rec_id ON recorrencias_historico (recorrencia_id);
CREATE INDEX IF NOT EXISTS idx_rec_hist_user ON recorrencias_historico (user_id);
CREATE INDEX IF NOT EXISTS idx_rec_parcelados_user ON recebimentos_parcelados (user_id, status);
CREATE INDEX IF NOT EXISTS idx_rec_parcelas_rec ON recebimentos_parcelas (recebimento_id);
CREATE INDEX IF NOT EXISTS idx_rec_parcelas_user ON recebimentos_parcelas (user_id, status);
CREATE INDEX IF NOT EXISTS idx_receita_tags_receita ON receita_tags (receita_id);
CREATE INDEX IF NOT EXISTS idx_receita_tags_tag ON receita_tags (tag_id);
CREATE INDEX IF NOT EXISTS idx_receitas_data ON receitas (data);
CREATE INDEX IF NOT EXISTS idx_receitas_recorrencia_id ON receitas (recorrencia_id);
CREATE INDEX IF NOT EXISTS idx_receitas_user_id ON receitas (user_id);
CREATE INDEX IF NOT EXISTS idx_regra_config_user ON regra_config (user_id);
CREATE INDEX IF NOT EXISTS idx_reserva_historico_reserva ON reserva_historico (reserva_id);
CREATE INDEX IF NOT EXISTS idx_reserva_historico_user ON reserva_historico (user_id, data);
CREATE INDEX IF NOT EXISTS idx_reserva_tags_reserva ON reserva_tags (reserva_id);
CREATE INDEX IF NOT EXISTS idx_reserva_tags_tag ON reserva_tags (tag_id);
CREATE INDEX IF NOT EXISTS idx_reserva_user ON reserva_emergencia (user_id);
CREATE INDEX IF NOT EXISTS idx_reserve_tx_reserve ON reserve_transactions (reserve_id);
CREATE INDEX IF NOT EXISTS idx_score_historico_user ON score_historico (user_id, mes DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions (token);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_shared_exp_user ON shared_expenses (user_id);
CREATE INDEX IF NOT EXISTS idx_shared_expenses_expense ON shared_expenses (expense_id);
CREATE INDEX IF NOT EXISTS idx_spec_reserves_user ON specialized_reserves (user_id, status);
CREATE INDEX IF NOT EXISTS idx_tag_despesas ON despesa_tags (tag_id);
CREATE INDEX IF NOT EXISTS idx_tags_auto_config_user ON tags_auto_config (user_id);
CREATE INDEX IF NOT EXISTS idx_tags_user ON tags (user_id);
CREATE INDEX IF NOT EXISTS idx_users_score_saude ON users (id, score_saude);
CREATE INDEX IF NOT EXISTS idx_weekly_challenge_config_user ON weekly_challenge_config (user_id);
CREATE INDEX IF NOT EXISTS idx_weekly_challenges_user ON weekly_challenges (user_id, year);
