-- 0003 — tabela de check-in do Diagnóstico 360°.
--
-- O frontend já chamava `GET` e `POST /api/ia/check-in` (app.js, linhas 14299 e
-- 14314) e havia um botão "Check-in" visível e habilitado na tela. Só que a
-- rota nunca existiu no backend: clicar mostrava dois toasts vermelhos com
-- "Request failed with status code 404" — a mensagem crua do axios.
--
-- O GET tinha `.catch(() => null)`, então falhava calado; o POST não, e era o
-- que o usuário via. Aqui entra o lado que faltava.

CREATE TABLE IF NOT EXISTS check_ins (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    integer NOT NULL,
  data       text NOT NULL,          -- YYYY-MM-DD do check-in
  mes        text NOT NULL,          -- YYYY-MM, para a sequência mensal
  score_no_dia integer,              -- foto do score no momento do check-in
  criado_em  text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  -- Um check-in por dia. O INSERT usa ON CONFLICT DO NOTHING e a rota responde
  -- "já registrado" em vez de duplicar.
  UNIQUE (user_id, data),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_check_ins_user_data ON check_ins (user_id, data DESC);
CREATE INDEX IF NOT EXISTS idx_check_ins_user_mes  ON check_ins (user_id, mes DESC);
