-- 0005 — bens patrimoniais (patrimônio não-financeiro).
--
-- Até aqui "patrimônio" no VerdeMais era só investimentos + reservas − dívidas.
-- Faltava a parte que costuma ser a MAIOR do patrimônio de uma família
-- brasileira: o imóvel, o carro, os equipamentos. Sem isso o número do
-- dashboard ficava negativo para quem financiou um apartamento — a dívida
-- entrava, o bem que ela comprou não.
--
-- Duas decisões que valem registro:
--
--  • `valor_aquisicao` e `valor_atual` são separados. Bem material quase nunca
--    vale o que se pagou: carro deprecia, imóvel costuma valorizar. Guardar os
--    dois permite mostrar o ganho/perda real em vez de fingir que o preço de
--    compra vale para sempre.
--
--  • `financiamento_id` liga o bem à dívida que o comprou. É o que evita a
--    contagem dobrada ao contrário: o app passa a poder dizer "o imóvel vale
--    R$ 400 mil e ainda deve R$ 180 mil", em vez de somar o bem e a dívida
--    como se não tivessem relação.

CREATE TABLE IF NOT EXISTS bens_patrimoniais (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          integer NOT NULL,
  nome             text NOT NULL,
  tipo             text NOT NULL DEFAULT 'outros'
                   CHECK (tipo IN ('imovel','veiculo','equipamento','joia','colecao','outros')),
  valor_aquisicao  double precision NOT NULL CHECK (valor_aquisicao >= 0),
  valor_atual      double precision NOT NULL CHECK (valor_atual >= 0),
  data_aquisicao   text,
  -- Ritmo anual esperado de mudança de valor, em %. Negativo = deprecia.
  -- Fica como referência do usuário; o valor exibido é sempre `valor_atual`.
  variacao_anual   double precision DEFAULT 0,
  -- Dívida que comprou este bem, quando houver.
  financiamento_id integer,
  -- Bem parado (imóvel em uso) x bem que pode virar dinheiro rápido.
  liquidez         text NOT NULL DEFAULT 'baixa'
                   CHECK (liquidez IN ('alta','media','baixa')),
  observacoes      text,
  ativo            integer NOT NULL DEFAULT 1,
  data_criacao     text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  data_atualizacao text DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_bens_user ON bens_patrimoniais (user_id, ativo);
