-- 0006 — catálogo de conquistas.
--
-- As 207 definições de conquista viviam só nas migrations do D1
-- (legado/migrations-d1/), e não vieram para o baseline do Postgres na
-- migração para o Neon. O efeito em produção é silencioso e total: a tabela
-- conquistas_definicoes está vazia, então a tela de Conquistas não lista
-- nada, /conquistas/novas faz JOIN com uma tabela vazia e nunca devolve
-- linha, e o overlay de "nova conquista" jamais dispara — ainda que
-- conquistas_usuario venha sendo populada esse tempo todo pelos INSERTs
-- espalhados pelas rotas.
--
-- Este arquivo traz o catálogo de volta. É idempotente (ON CONFLICT DO
-- NOTHING pelo codigo), então rodar de novo não duplica nem sobrescreve.

INSERT INTO conquistas_definicoes (codigo, titulo, descricao, icone, categoria, plano_requerido, pontos, raridade) VALUES
  ('primeira_receita', 'Primeira Receita', 'Registrou sua primeira receita', '💰', 'financas', 'free', 10, 'comum'),
  ('sonhador', 'Sonhador', 'Criou sua primeira meta financeira', '🎯', 'metas', 'free', 15, 'comum'),
  ('organizador', 'Organizador', 'Registrou sua primeira despesa', '📋', 'financas', 'free', 10, 'comum'),
  ('investidor', 'Investidor', 'Registrou seu primeiro investimento', '📈', 'investimentos', 'free', 20, 'comum'),
  ('planejador', 'Planejador', 'Completou o perfil financeiro', '🧠', 'perfil', 'free', 25, 'raro'),
  ('carteirinha', 'Carteirinha', 'Cadastrou seu primeiro cartão', '💳', 'cartoes', 'free', 15, 'comum'),
  ('disciplinado', 'Disciplinado', 'Pagou 10 despesas em um mesmo mês', '💪', 'geral', 'free', 30, 'comum'),
  ('meta_concluida', 'Conquistador', 'Concluiu sua primeira meta financeira', '🏆', 'metas', 'free', 50, 'epico'),
  ('sem_dividas', 'Livre de Dívidas', 'Quitou todas as dívidas cadastradas', '🏆', 'geral', 'free', 200, 'comum'),
  ('poupador', 'Poupador', 'Poupou mais de 20% da renda em um mês', '🐷', 'geral', 'free', 40, 'raro'),
  ('milionario', 'Rumo ao Milhão', 'Acumula mais de R$ 100.000 investidos', '💰', 'geral', 'free', 100, 'lendario'),
  ('cartao_zero', 'Fatura Zero', 'Pagou a fatura completa do cartão', '✅', 'cartoes', 'free', 20, 'comum'),
  ('lembrete_mestre', 'Mestre dos Lembretes', 'Registrou 5 contas no mesmo mês', '⏰', 'lembretes', 'free', 20, 'comum'),
  ('analista', '📊 Analista Financeiro', 'Consultou o relatório anual', '🏆', 'analises', 'free', 30, 'comum'),
  ('primeiro_imovel', 'Proprietário!', 'Cadastrou seu primeiro financiamento imobiliário', '🏠', 'patrimonio', 'free', 50, 'epico'),
  ('quitou_10pct', 'Primeiros 10%', 'Quitou 10% do financiamento imobiliário', '🔑', 'patrimonio', 'free', 30, 'raro'),
  ('quitou_15pct', 'Conquistando Espaço', 'Quitou 15% do imóvel', '🏡', 'patrimonio', 'free', 40, 'raro'),
  ('quitou_20pct', 'Quinto do Imóvel', 'Quitou 20% do imóvel', '🏘️', 'patrimonio', 'premium', 50, 'raro'),
  ('quitou_30pct', 'Terço do Caminho', 'Quitou 30% do imóvel', '🌆', 'patrimonio', 'premium', 60, 'epico'),
  ('quitou_50pct', 'Metade sua!', 'Quitou 50% do imóvel', '🏙️', 'patrimonio', 'premium', 100, 'epico'),
  ('imovel_quitado', 'Imóvel Quitado!', 'Quitou completamente seu imóvel', '🎉', 'patrimonio', 'premium', 200, 'lendario'),
  ('primeiro_carro', 'De Rodas!', 'Cadastrou seu primeiro financiamento de veículo', '🚗', 'patrimonio', 'free', 30, 'raro'),
  ('carro_quitado', 'Carro Quitado!', 'Quitou completamente seu veículo', '🏎️', 'patrimonio', 'free', 100, 'epico'),
  ('sem_dividas_total', 'Livre de Tudo!', 'Quitou todos os empréstimos e financiamentos', '🦅', 'dividas', 'premium', 150, 'lendario'),
  ('investidor_cdi', 'Rendendo CDI', 'Criou uma Caixinha de investimento', '💰', 'investimentos', 'free', 20, 'comum'),
  ('poupador_dedicado', 'Poupador Dedicado', 'Tem mais de R$ 10.000 em investimentos', '💎', 'investimentos', 'premium', 60, 'epico'),
  ('investidor_acoes', 'Investidor da Bolsa', 'Cadastrou um investimento em ações', '📊', 'geral', 'free', 30, 'raro'),
  ('investidor_fii', 'Renda Passiva Imobiliária', 'Cadastrou um FII', '🏢', 'geral', 'free', 30, 'raro'),
  ('investidor_cripto', 'Crypto Holder', 'Cadastrou criptomoedas', '₿', 'geral', 'free', 25, 'raro'),
  ('investidor_tesouro', 'Tesouro Nacional', 'Investiu no Tesouro Direto', '🏛️', 'geral', 'free', 25, 'comum'),
  ('investidor_cdb', 'Renda Fixa Sólida', 'Cadastrou um CDB', '🏦', 'geral', 'free', 20, 'comum'),
  ('investidor_diversificado', 'Portfólio Diversificado', 'Tem 3 tipos diferentes de investimentos', '🎯', 'geral', 'free', 50, 'epico'),
  ('reserva_iniciada', 'Primeiro Escudo', 'Criou sua reserva de emergência — o primeiro passo é o mais importante', '🛡️', 'marco', 'free', 25, 'comum'),
  ('reserva_1_mes', 'Reserva: 1 Mês', 'Reserva cobre 1 mês de despesas', '🛡️', 'geral', 'free', 40, 'raro'),
  ('reserva_3_meses', 'Reserva: 3 Meses', 'Reserva cobre 3 meses de despesas', '🛡️', 'geral', 'free', 60, 'epico'),
  ('reserva_6_meses', 'Reserva: 6 Meses', 'Reserva cobre 6 meses de despesas', '🦺', 'geral', 'free', 80, 'epico'),
  ('reserva_completa', 'Reserva Completa!', 'Atingiu 100% da meta da reserva', '🏰', 'geral', 'free', 100, 'lendario'),
  ('meta_casa', 'Sonho da Casa Própria', 'Meta de imóvel criada', '🏠', 'geral', 'free', 30, 'raro'),
  ('meta_carro', 'Meta do Carro', 'Meta de veículo criada', '🚗', 'geral', 'free', 25, 'comum'),
  ('meta_viagem', 'Explorador', 'Meta de viagem criada', '✈️', 'geral', 'free', 20, 'comum'),
  ('meta_educacao', 'Investindo no Futuro', 'Meta de educação criada', '📚', 'geral', 'free', 25, 'comum'),
  ('meta_liberdade', 'Liberdade Financeira', 'Meta de liberdade financeira criada', '🦅', 'geral', 'free', 40, 'raro'),
  ('meta_aposentadoria', 'Aposentadoria Planejada', 'Meta de aposentadoria criada', '🌴', 'geral', 'free', 40, 'raro'),
  ('amortizou', 'Pagou a Mais', 'Realizou uma amortização extraordinária', '⚡', 'geral', 'free', 40, 'raro'),
  ('financiamento_veiculo', 'Financiou um Veículo', 'Tem financiamento de veículo', '🚗', 'geral', 'free', 20, 'comum'),
  ('financiamento_outros', 'Outros Financiamentos', 'Cadastrou financiamento de outros bens', '📋', 'geral', 'free', 20, 'comum'),
  ('orcamentista', 'Orcamentista', 'Criou seu primeiro orçamento por categoria', '📊', 'geral', 'free', 25, 'comum'),
  ('controlador', 'Controlador', 'Manteve todos os orçamentos no verde por 1 mês', '✅', 'geral', 'free', 50, 'comum'),
  ('automatico', 'Piloto Automático', 'Configurou sua primeira transação recorrente', '🔄', 'geral', 'free', 25, 'comum'),
  ('recorrente_pro', 'Rotina Financeira', 'Tem 5 ou mais recorrências ativas', '⚙️', 'geral', 'free', 75, 'comum'),
  ('assinante', 'Membro Premium', 'Assinou o plano Premium ou Pro do VerdeMais', '⭐', 'geral', 'free', 100, 'comum'),
  ('projetor', '🔮 Projetor Financeiro', 'Consultou a projeção financeira', '🏆', 'analises', 'free', 20, 'comum'),
  ('fatura_paga', 'Fatura Quitada', 'Pagou uma fatura completa do cartão', '💳', 'geral', 'free', 30, 'comum'),
  ('meta_divida', 'Devedor Consciente', 'Criou uma meta para quitar uma dívida', '🎯', 'geral', 'free', 40, 'comum'),
  ('tagger', '🏷️ Organizador', 'Usou tags em 5 ou mais despesas', '🏆', 'habitos', 'free', 40, 'comum'),
  ('comparador', 'Analítico', 'Consultou o comparativo mês a mês', '📊', 'geral', 'free', 20, 'comum'),
  ('exportador', 'Profissional', 'Exportou seu primeiro relatório financeiro', '📄', 'geral', 'free', 30, 'comum'),
  ('sem_alertas', 'Cartão Limpo', 'Ficou 30 dias sem alertas de cartão', '✅', 'geral', 'free', 50, 'comum'),
  ('multi_reserva_criada', '🗂️ Múltiplas Reservas', 'Criou uma reserva especializada', '🏆', 'reservas', 'free', 20, 'comum'),
  ('multi_3_reservas', '🏦 Gestor de Reservas', 'Possui 3 ou mais reservas ativas', '🏆', 'reservas', 'free', 100, 'epico'),
  ('reserva_spec_completa', '🛡️ Reserva Completa', 'Completou uma reserva especializada', '🏆', 'reservas', 'free', 100, 'raro'),
  ('sub_detector_scanned', '🔍 Detector Ativo', 'Rodou o detector de assinaturas fantasma', '🏆', 'v3', 'free', 20, 'comum'),
  ('sub_cancelou_1', '✂️ Poda das Assinaturas', 'Cancelou uma assinatura detectada', '🏆', 'v3', 'free', 40, 'comum'),
  ('desafio_52_iniciou', '🗓️ Desafio Iniciado', 'Iniciou o Desafio 52 Semanas', '🏆', 'desafio52', 'free', 20, 'comum'),
  ('desafio_52_metade', '🎯 Metade do Desafio', 'Concluiu 26 semanas do Desafio 52', '🏆', 'desafio52', 'free', 100, 'raro'),
  ('desafio_52_completo', '🏅 Desafio 52 Completo!', 'Completou todas as 52 semanas', '🏆', 'desafio52', 'free', 500, 'lendario'),
  ('amortizou_simulou', '📐 Simulou Amortização', 'Usou o simulador de amortização inteligente', '🏆', 'v3', 'free', 30, 'comum'),
  ('regra_503020_verde', '⚖️ Equilíbrio 50/30/20', 'Atingiu score ≥ 80 na regra 50/30/20', '🏆', 'habitos', 'free', 80, 'raro'),
  ('quitou_imovel', '🏠 Livre do Imóvel!', 'Quitou um financiamento imobiliário', '🏆', 'dividas', 'free', 500, 'lendario'),
  ('saldo_verde_3m', '💚 3 Meses no Verde', 'Manteve saldo positivo por 3 meses seguidos', '🏆', 'habitos', 'free', 50, 'raro'),
  ('zero_divida_cartao', 'Zero Dívida no Cartão', 'Fatura zerada por 3 meses consecutivos', '💳', 'geral', 'free', 60, 'epico'),
  ('barreira_10k', '💰 Barreira dos 10 Mil', 'Patrimônio investido atingiu R$ 10.000', '🏆', 'investimentos', 'free', 100, 'epico'),
  ('barreira_50k', '🚀 Barreira dos 50 Mil', 'Patrimônio investido atingiu R$ 50.000', '🏆', 'investimentos', 'free', 250, 'epico'),
  ('realizador', '🏆 Realizador', 'Concluiu 3 metas financeiras', '🏆', 'metas', 'free', 150, 'epico'),
  ('aporta_todo_mes', 'Investidor Consistente', 'Realizou aportes por 3 meses seguidos', '📈', 'geral', 'free', 60, 'epico'),
  ('carteira_diversa', 'Carteira Diversificada', 'Tem investimentos em 5 ou mais categorias diferentes', '🌐', 'geral', 'free', 100, 'epico'),
  ('orcamento_completo', 'Planejador Mestre', 'Configurou orçamentos para todas as categorias', '📊', 'geral', 'free', 40, 'raro'),
  ('regra_3meses', 'Regra na Veia', 'Score 50/30/20 acima de 70 por 3 meses seguidos', '⚖️', 'geral', 'free', 100, 'epico'),
  ('desafio_trimestre', 'Quarteirão Completo', 'Completou as primeiras 13 semanas do Desafio 52', '🗓️', 'geral', 'free', 50, 'raro'),
  ('livre_emprestimo', 'Crédito Livre', 'Quitou todos os empréstimos pessoais', '🔓', 'geral', 'free', 75, 'epico'),
  ('50pct_financiamento', 'Metade da Jornada', 'Quitou 50% do financiamento imobiliário', '🏗️', 'geral', 'free', 100, 'epico'),
  ('reserva_12_meses', 'Reserva Completa! 🏆', 'Reserva cobre 12 meses de despesas — independência total de emergências!', '💎', 'geral', 'free', 100, 'lendario'),
  ('todas_reservas_ok', 'Proteção Total', 'Todas as reservas especializadas completadas', '🛡️', 'geral', 'free', 150, 'lendario'),
  ('sem_gastos_luxo', 'Consciência Financeira', 'Mês sem gastos em Lazer/Entretenimento acima de R$500', '🧘', 'geral', 'free', 40, 'raro'),
  ('renda_extra', 'Multitalento', 'Registrou receitas de 3 fontes diferentes no mês', '💼', 'geral', 'free', 35, 'raro'),
  ('sem_atraso', 'Pontualidade Total', '3 meses sem despesas vencidas sem pagar', '⏰', 'geral', 'free', 45, 'raro'),
  ('detector_expert', 'Caçador de Fantasmas', 'Cancelou 5 assinaturas via Detector', '👻', 'geral', 'free', 80, 'epico'),
  ('amortizador_serie', 'Mago da Amortização', 'Fez 5 simulações de amortização', '🧮', 'geral', 'free', 50, 'raro'),
  ('desafio_52_5meses', 'Persistência', 'Completou 22 semanas do Desafio 52', '💪', 'geral', 'free', 60, 'epico'),
  ('primeiro_milhao', 'O Primeiro Milhão', 'Patrimônio líquido atingiu R$ 1.000.000', '💎', 'geral', 'free', 1000, 'lendario'),
  ('crescimento_anual', 'Crescimento Anual', 'Patrimônio cresceu mais de 20% em 12 meses', '📊', 'geral', 'free', 120, 'epico'),
  ('zero_dividas_cartao', '💳 Zero no Cartão', 'Pagou a fatura completa 3 meses consecutivos', '🏆', 'cartoes', 'free', 75, 'raro'),
  ('barreira_100k', '💎 Barreira dos 100 Mil', 'Patrimônio investido atingiu R$ 100.000', '🏆', 'investimentos', 'free', 500, 'lendario'),
  ('livre_do_banco', '🏦 Livre do Banco!', 'Quitou todos os empréstimos ativos', '🏆', 'dividas', 'free', 200, 'lendario'),
  ('investidor_veteran', '📊 Veterano dos Investimentos', 'Possui 5 ou mais tipos de investimento', '🏆', 'investimentos', 'free', 200, 'lendario'),
  ('login_diario', 'Usuário Fiel', 'Fez login por 7 dias consecutivos', '🗓️', 'geral', 'free', 30, 'raro'),
  ('perfil_completo', 'Perfil Completo', 'Preencheu todas as informações do perfil', '👤', 'geral', 'free', 20, 'comum'),
  ('exportador_dados', 'Exportador de Dados', 'Exportou relatório em PDF ou Excel pela primeira vez', '📤', 'geral', 'free', 25, 'comum'),
  ('primeira_tag', 'Tagger', 'Criou sua primeira tag de organização', '🏷️', 'geral', 'free', 15, 'comum'),
  ('mestre_tags', 'Mestre das Tags', 'Classificou 50 despesas com tags', '🔖', 'geral', 'free', 40, 'raro'),
  ('detector_assinatura', 'Caçador de Fantasmas', 'Detectou e cancelou pelo menos 1 assinatura fantasma', '👻', 'geral', 'free', 35, 'raro'),
  ('primeiro_orcamento', 'Planejador Iniciante', 'Criou o primeiro orçamento por categoria', '📝', 'geral', 'free', 15, 'comum'),
  ('saude_ferro', 'Saúde de Ferro', 'Atingiu Score de Saúde acima de 90 pontos', '💪', 'geral', 'free', 100, 'lendario'),
  ('recuperacao', 'Grande Recuperação', 'Aumentou o Score de Saúde em 10+ pontos em um único mês', '📈', 'geral', 'free', 75, 'epico'),
  ('score_50', 'Na Média', 'Score de Saúde superou 50 pela primeira vez', '⭐', 'geral', 'free', 20, 'comum'),
  ('score_70', 'Boa Saúde', 'Score de Saúde superou 70 pela primeira vez', '✨', 'geral', 'free', 50, 'raro'),
  ('score_80', 'Excelente Saúde', 'Score de Saúde superou 80 pela primeira vez', '🌟', 'geral', 'free', 75, 'epico'),
  ('curioso', 'Curioso', 'Consultou o relatório anual 3 ou mais vezes', '🔍', 'geral', 'free', 25, 'comum'),
  ('analitico', 'Analítico', 'Usou o comparativo mensal 5 ou mais vezes', '🧠', 'geral', 'free', 40, 'raro'),
  ('projecao_vista', 'Visionário', 'Consultou a Projeção Financeira pela primeira vez', '🔮', 'geral', 'free', 20, 'comum'),
  ('ia_power_user', 'IA Power User', 'Fez 20 ou mais perguntas ao Assistente VerdeMais', '🤖', 'geral', 'free', 50, 'raro'),
  ('poupador_3m', 'Poupador Consistente', 'Taxa de poupança acima de 20% por 3 meses consecutivos', '🐷', 'geral', 'free', 80, 'epico'),
  ('zero_atraso_3m', 'Sem Atrasos', 'Nenhuma despesa atrasada por 3 meses consecutivos', '⏰', 'geral', 'free', 60, 'epico'),
  ('investidor_mensal', 'Aportador Mensal', 'Realizou aportes em investimentos por 3 meses seguidos', '💰', 'geral', 'free', 60, 'epico'),
  ('diversificador', 'Diversificador', 'Tem investimentos em 4 tipos diferentes ao mesmo tempo', '🌐', 'geral', 'free', 50, 'raro'),
  ('meta_rapida', 'Velocista', 'Concluiu uma meta financeira em menos de 30 dias', '⚡', 'geral', 'free', 40, 'raro'),
  ('super_reserva', 'Super Reserva', 'Atingiu 12 meses de reserva de emergência', '🛡️', 'geral', 'free', 120, 'lendario'),
  ('7_dias_lancando', 'Semana Registrada', 'Registrou despesas ou receitas por 7 dias seguidos', '📅', 'habito', 'free', 30, 'raro'),
  ('30_dias_lancando', 'Mês Completo', 'Registrou lançamentos por 30 dias consecutivos — hábito consolidado!', '🗓️', 'habito', 'free', 80, 'epico'),
  ('acesso_5_dias', 'Presença Constante', 'Acessou o VerdeMais por 5 dias seguidos', '🔥', 'habito', 'free', 20, 'comum'),
  ('3_meses_ativos', 'Trimestre Ativo', 'Manteve o controle financeiro por 3 meses diferentes', '📆', 'habito', 'free', 50, 'raro'),
  ('6_meses_receita', 'Renda Monitorada', 'Cadastrou receita em pelo menos 6 meses diferentes', '💹', 'habito', 'free', 80, 'epico'),
  ('10_despesas_pagas', 'Comprometido', 'Marcou 10 despesas como pagas — sem deixar dívida', '✅', 'despesas', 'free', 25, 'comum'),
  ('50_despesas_pagas', 'Pagador em Dia', 'Marcou 50 despesas como pagas', '🏅', 'despesas', 'free', 60, 'raro'),
  ('20_despesas_com_tag', 'Organizador de Elite', 'Categorizou 20 despesas com tags personalizadas', '🏷️', 'despesas', 'free', 40, 'raro'),
  ('mes_zerado', 'Mês Zerado', 'Encerrou o mês sem nenhuma despesa pendente', '🧹', 'despesas', 'free', 50, 'raro'),
  ('5_receitas', 'Renda Registrada', 'Cadastrou 5 fontes de receita', '💵', 'receitas', 'free', 20, 'comum'),
  ('receita_diversificada', 'Múltiplas Fontes', 'Cadastrou receitas de 3 categorias diferentes', '🌊', 'receitas', 'free', 50, 'raro'),
  ('receita_5k', 'Cinco Mil no Bolso', 'Registrou renda mensal acima de R$ 5.000', '💸', 'receitas', 'free', 40, 'raro'),
  ('3_metas_concluidas', 'Tricampeão de Metas', 'Concluiu 3 metas financeiras — determinação real', '🥇', 'metas', 'free', 100, 'epico'),
  ('meta_antes_prazo', 'Adiantado', 'Concluiu uma meta antes da data prevista', '⚡', 'metas', 'free', 75, 'epico'),
  ('5_metas_ativas', 'Ambicioso', 'Mantém 5 metas ativas simultaneamente', '🎯', 'metas', 'free', 30, 'raro'),
  ('meta_grande', 'Grande Objetivo', 'Criou uma meta com valor acima de R$ 10.000', '🏔️', 'metas', 'free', 35, 'raro'),
  ('investiu_mais_que_gastou', 'Modo Acumulação', 'Investiu mais do que gastou em um único mês', '📊', 'investimentos', 'free', 80, 'epico'),
  ('5_investimentos', 'Carteira Ativa', 'Mantém 5 investimentos cadastrados', '💼', 'investimentos', 'free', 40, 'raro'),
  ('primeiro_lucro', 'Primeiro Lucro', 'Obteve rentabilidade positiva em um investimento', '🌱', 'investimentos', 'free', 30, 'comum'),
  ('aporte_3_meses', 'Aportes Frequentes', 'Realizou aportes em investimentos por 3 meses consecutivos', '🔁', 'investimentos', 'free', 60, 'raro'),
  ('patrimonio_positivo', 'No Azul', 'Patrimônio líquido positivo — você tem mais do que deve!', '🟢', 'investimentos', 'free', 50, 'raro'),
  ('3_orcamentos', 'Controlador de Gastos', 'Criou 3 orçamentos mensais para controlar categorias', '📊', 'orcamentos', 'free', 25, 'comum'),
  ('orcamentos_no_limite', 'Dentro do Limite', 'Não ultrapassou nenhum orçamento em um mês completo', '🎖️', 'orcamentos', 'free', 70, 'epico'),
  ('fatura_em_dia', 'Fatura Quitada', 'Pagou a fatura do cartão antes do vencimento', '💳', 'cartoes', 'free', 30, 'comum'),
  ('fatura_saudavel', 'Fatura Saudável', 'Manteve a fatura abaixo de 30% do limite do cartão', '💚', 'cartoes', 'free', 40, 'raro'),
  ('lembrete_pontual', 'Pontual', 'Marcou 10 lembretes como concluídos antes de vencer', '⏱️', 'lembretes', 'free', 40, 'raro'),
  ('10_lembretes', 'Cheio de Alertas', 'Criou 10 lembretes financeiros', '🔔', 'lembretes', 'free', 25, 'comum'),
  ('score_90', 'Elite Financeira', 'Atingiu score de saúde financeira acima de 90', '👑', 'saude', 'free', 150, 'lendario'),
  ('saldo_positivo_3m', 'Três Meses no Verde', 'Manteve saldo positivo por 3 meses consecutivos', '🌿', 'saude', 'free', 100, 'epico'),
  ('necessidades_50pct', 'Regra dos 50', 'Manteve gastos com necessidades abaixo de 50% da renda', '⚖️', 'saude', 'free', 60, 'raro'),
  ('primeiro_saldo_positivo', 'Primeiro Verde', 'Terminou o mês com mais receitas do que despesas pela 1ª vez', '🌱', 'marco', 'free', 20, 'comum'),
  ('reduziu_divida_20', 'Atacando a Dívida', 'Reduziu o saldo devedor total em 20% em um único mês', '⚔️', 'marco', 'free', 80, 'epico'),
  ('desafio_52_1k', 'Mil no Desafio', 'Acumulou R$ 1.000 no Desafio 52 Semanas', '🎉', 'desafio', 'free', 50, 'raro'),
  ('desafio_52_10sem', 'Dez Semanas', 'Completou 10 semanas no Desafio 52 Semanas', '💪', 'desafio', 'free', 40, 'raro'),
  ('usou_ia', 'Consultor Digital', 'Usou a análise com IA pela primeira vez', '🤖', 'engajamento', 'free', 20, 'comum'),
  ('usou_simulador', 'Estrategista', 'Usou o simulador de investimentos', '🧮', 'engajamento', 'free', 20, 'comum'),
  ('viu_projecao', '🔭 Olho no Futuro', 'Visualizou projeção de investimentos', '🔭', 'investimentos', 'free', 15, 'comum'),
  ('usuario_completo', '🌟 VerdeMais Completo', 'Tem receita, despesa, investimento, meta e reserva cadastrados — parabéns!', '🌟', 'engajamento', 'free', 100, 'epico'),
  ('primeira_assinatura', 'Assinante', 'Cadastrou sua primeira assinatura recorrente', '📱', 'assinaturas', 'free', 10, 'comum'),
  ('cortou_gordura', 'Corte Cirúrgico', 'Cancelou uma assinatura detectada como desnecessária', '✂️', 'assinaturas', 'free', 40, 'raro'),
  ('assinaturas_organizadas', 'Controle Total', 'Categorizou todas as suas assinaturas', '🗂️', 'assinaturas', 'free', 30, 'raro'),
  ('assinatura_econômico', 'Consumo Consciente', 'Mantém gastos com assinaturas abaixo de R$ 200/mês', '💡', 'assinaturas', 'free', 50, 'raro'),
  ('primeira_recorrencia', 'Automação Financeira', 'Criou sua primeira despesa recorrente', '🔄', 'recorrencias', 'free', 15, 'comum'),
  ('3_recorrencias', 'Rotina Planejada', 'Mantém 3 ou mais despesas recorrentes cadastradas', '⚙️', 'recorrencias', 'free', 25, 'comum'),
  ('recorrencias_dia', 'Compromisso Cumprido', 'Pagou todas as recorrências do mês em dia', '✔️', 'recorrencias', 'free', 45, 'raro'),
  ('primeiro_financiamento', 'Financiado', 'Cadastrou seu primeiro financiamento', '🏦', 'financiamentos', 'free', 10, 'comum'),
  ('um_ano_financiamento', 'Um Ano Pagando', 'Completou 12 meses de pagamento em um financiamento', '📅', 'financiamentos', 'free', 80, 'epico'),
  ('amortizou_antecipado', 'Atacou a Dívida', 'Realizou amortização antecipada em um financiamento', '⚡', 'financiamentos', 'free', 60, 'raro'),
  ('metade_paga', 'Meio Caminho', 'Já pagou mais de metade de um financiamento', '🏁', 'financiamentos', 'free', 100, 'epico'),
  ('primeiro_emprestimo', 'Registrei Minha Dívida', 'Cadastrou seu primeiro empréstimo — transparência é o primeiro passo', '📝', 'emprestimos', 'free', 10, 'comum'),
  ('emprestimo_quitado', 'Dívida Zerada', 'Quitou um empréstimo por completo', '🎉', 'emprestimos', 'free', 150, 'epico'),
  ('emprestimo_sem_atraso', 'Devedor Honesto', 'Nunca atrasou uma parcela de empréstimo', '🤝', 'emprestimos', 'free', 70, 'epico'),
  ('dois_cartoes', 'Multi Cartões', 'Cadastrou 2 cartões de crédito', '💳', 'cartoes', 'free', 15, 'comum'),
  ('cinco_cartoes', 'Colecionador de Cartões', 'Cadastrou 5 cartões de crédito', '🃏', 'cartoes', 'free', 30, 'raro'),
  ('limite_10k', 'Crédito de Peso', 'Soma dos limites dos cartões ultrapassa R$ 10.000', '💰', 'cartoes', 'free', 40, 'raro'),
  ('uso_baixo_cartao', 'Cartão Responsável', 'Usou menos de 10% do limite disponível em um mês', '🛡️', 'cartoes', 'free', 50, 'epico'),
  ('lembrete_fatura', 'Alerta de Fatura', 'Criou um lembrete para vencimento de fatura de cartão', '📬', 'lembretes', 'free', 15, 'comum'),
  ('3_lembretes_ativos', 'Sempre Atento', 'Mantém 3 ou mais lembretes ativos simultaneamente', '🔔', 'lembretes', 'free', 20, 'comum'),
  ('20_lembretes_concluidos', 'Missão Cumprida', 'Concluiu 20 lembretes financeiros', '✅', 'lembretes', 'free', 60, 'raro'),
  ('renda_de_investimento', 'Dinheiro Trabalhando', 'Registrou renda proveniente de investimentos', '🌿', 'receitas', 'free', 40, 'raro'),
  ('renda_extra_cadastrada', 'Freelancer', 'Cadastrou uma renda extra além do salário principal', '💼', 'receitas', 'free', 25, 'comum'),
  ('receita_10k', 'Renda de 5 Dígitos', 'Registrou renda mensal acima de R$ 10.000', '🚀', 'receitas', 'free', 100, 'epico'),
  ('primeiro_aporte_meta', 'Primeiros Passos', 'Fez o primeiro aporte em uma meta financeira', '👟', 'metas', 'free', 15, 'comum'),
  ('meta_educacao_concluida', 'Investi em Mim', 'Concluiu uma meta de educação ou desenvolvimento pessoal', '🎓', 'metas', 'free', 80, 'epico'),
  ('meta_viagem_concluida', 'Passagem Garantida', 'Concluiu uma meta de viagem', '✈️', 'metas', 'free', 80, 'epico'),
  ('pensa_no_futuro', 'Pensa no Futuro', 'Criou uma meta de aposentadoria ou independência financeira', '🏖️', 'metas', 'free', 50, 'raro'),
  ('score_melhorou', 'Subindo na Vida', 'Melhorou o score de saúde financeira em um mês', '📈', 'saude', 'free', 30, 'raro'),
  ('score_80_3m', '💎 Consistência Premium', 'Manteve score acima de 80 por 3 meses consecutivos', '💎', 'saude', 'free', 100, 'comum'),
  ('login_30_dias', 'Fiel ao App', 'Acessou o VerdeMais por 30 dias consecutivos', '📲', 'engajamento', 'free', 100, 'epico'),
  ('usou_comparativo_cdi', 'Comparador de Taxas', 'Consultou o comparativo CDI nos investimentos', '📊', 'engajamento', 'free', 15, 'comum'),
  ('primeiro_relatorio', 'Relatório Gerado', 'Exportou seus dados financeiros pela primeira vez', '📄', 'engajamento', 'free', 20, 'comum'),
  ('usou_filtros', 'Analista Preciso', 'Usou filtros avançados para analisar seus lançamentos', '🔍', 'engajamento', 'free', 15, 'comum'),
  ('patrimonio_500k', '💎 Meio Milhão', 'Patrimônio líquido ultrapassou R$ 500.000', '💎', 'marco', 'free', 500, 'lendario'),
  ('2_anos_verde', 'Dois Anos no Verde', 'Usa o VerdeMais há mais de 2 anos', '🎂', 'engajamento', 'free', 200, 'lendario'),
  ('score_100', '🌟 Saúde Perfeita', 'Atingiu score de saúde financeira máximo: 100', '🌟', 'saude', 'free', 500, 'lendario'),
  ('reduziu_3_categorias', 'Tesoura Afiada', 'Reduziu gastos em 3 categorias diferentes num mesmo mês', '✂️', 'despesas', 'free', 80, 'epico'),
  ('100_transacoes', 'Centurião Financeiro', 'Registrou mais de 100 transações no VerdeMais', '💯', 'habito', 'free', 60, 'raro'),
  ('500_transacoes', 'Arquivista de Elite', 'Registrou mais de 500 transações — controle total!', '🗄️', 'habito', 'free', 150, 'lendario'),
  ('reserva_9_meses', 'Reserva: 9 Meses', 'Sua reserva cobre 9 meses de despesas — você está protegido!', '🛡️', 'geral', 'free', 80, 'epico'),
  ('score_80_1m', '📈 No Caminho Certo', 'Manteve score acima de 80 por 1 mês', '📈', 'saude', 'free', 30, 'comum'),
  ('score_80_2m', '🔥 Em Chama', 'Manteve score acima de 80 por 2 meses consecutivos', '🔥', 'saude', 'free', 50, 'comum'),
  ('aporte_recorrente', '🔄 Investidor Disciplinado', 'Fez aportes em 3 meses consecutivos', '🔄', 'investimentos', 'free', 60, 'comum'),
  ('quita_divida', '🏆 Quitador', 'Quitou uma dívida ou empréstimo', '🏆', 'dividas', 'free', 80, 'comum'),
  ('sem_cartao_devedor', '💳 Cartão em Dia', 'Ficou 3 meses sem dívida no cartão de crédito', '💳', 'cartoes', 'free', 70, 'comum'),
  ('orcamento_cumprido', '✅ Orçamento Cumprido', 'Cumpriu o orçamento mensal sem ultrapassar', '✅', 'orcamento', 'free', 50, 'comum'),
  ('3_metas_meta_concluidas', '🎯 Realizador', 'Concluiu 3 metas financeiras', '🎯', 'metas', 'free', 90, 'comum'),
  ('primeira_antecipacao', '⚡ Antecipador', 'Antecipou o pagamento de uma conta pela primeira vez', '⚡', 'dividas', 'free', 40, 'comum'),
  ('3_antecipacoes', '🔥 Mestre da Antecipação', 'Antecipou 3 contas ou mais', '🔥', 'dividas', 'free', 80, 'comum'),
  ('primeiro_recebimento_parcelado', '📋 Controlador', 'Cadastrou seu primeiro recebimento parcelado', '📋', 'receitas', 'free', 30, 'comum'),
  ('recebimento_concluido', '🎉 Recebeu Tudo', 'Concluiu o recebimento de todas as parcelas de um acordo', '🎉', 'receitas', 'free', 100, 'comum')
ON CONFLICT (codigo) DO NOTHING;
