-- 0008 — a identidade do gasto, e o desfazer que ela exige.
--
-- Medido nesta base: 834 despesas, 659 descrições distintas, 222 coisas de
-- verdade depois de normalizar. "Gasolina" em três categorias ao mesmo tempo;
-- "MP CAIXAECONOMICAFEDERAL", 63 lançamentos e R$ 9.162,83, partido entre
-- Financiamentos e Moradia. Enquanto o sistema não souber que dois lançamentos
-- são a mesma coisa, nenhum relatório por categoria está certo, nenhum
-- orçamento faz sentido e nenhuma recorrência é detectada.
--
-- Duas tabelas:
--
--   identidades          — QUEM é o gasto. Estável, uma categoria só, guarda
--                          a decisão do usuário para valer também no que ele
--                          lançar amanhã.
--   organizador_acoes    — o que foi aplicado e como voltar atrás. Sem isto,
--                          "aplicar aos 63" é uma aposta irreversível — e o
--                          usuário certo é o que não aposta.

-- ── Identidade ──────────────────────────────────────────────────────────────
-- `chave` é a descrição normalizada (camada 1) OU o carimbo do contrato
-- (camada 2, no formato "@emprestimo:7"). É ela que agrupa, não o nome: o
-- nome é só o rótulo bonito, e muda quando o usuário quiser.
CREATE TABLE IF NOT EXISTS identidades (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     integer NOT NULL,
  chave       text    NOT NULL,
  nome        text    NOT NULL,
  categoria   text,
  -- 'auto'    → o sistema deduziu e ninguém confirmou
  -- 'usuario' → alguém decidiu na Central; não mexer sem perguntar de novo
  -- 'sistema' → veio de vínculo (empréstimo, financiamento, recorrência)
  origem      text    NOT NULL DEFAULT 'auto' CHECK(origem IN ('auto','usuario','sistema')),
  confirmada  integer NOT NULL DEFAULT 0,
  -- Quando o usuário aceita que duas identidades são a mesma coisa, a menor
  -- aponta para a maior por aqui em vez de ser apagada. Apagar perderia a
  -- chave, e a chave é o que reconhece o próximo lançamento com aquele texto.
  chave_mestre text,
  created_at  text    DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  updated_at  text    DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(user_id, chave)
);

CREATE INDEX IF NOT EXISTS idx_identidades_user ON identidades (user_id);
CREATE INDEX IF NOT EXISTS idx_identidades_cat  ON identidades (user_id, categoria);

ALTER TABLE identidades DROP CONSTRAINT IF EXISTS identidades_user_fk;
ALTER TABLE identidades ADD CONSTRAINT identidades_user_fk
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- A despesa aponta para a identidade. Fica NULL até a primeira indexação —
-- e continua funcionando NULL, porque toda leitura cai de volta na descrição.
-- Nada nesta migration quebra se a indexação nunca rodar.
ALTER TABLE despesas ADD COLUMN IF NOT EXISTS identidade_id integer;
CREATE INDEX IF NOT EXISTS idx_despesas_identidade ON despesas (identidade_id);

ALTER TABLE despesas DROP CONSTRAINT IF EXISTS despesas_identidade_fk;
ALTER TABLE despesas ADD CONSTRAINT despesas_identidade_fk
  FOREIGN KEY (identidade_id) REFERENCES identidades(id) ON DELETE SET NULL;

-- ── Desfazer ────────────────────────────────────────────────────────────────
-- `antes` guarda o estado anterior linha a linha, em JSON:
--   [{"id": 412, "categoria": "Moradia"}, ...]
--
-- Guardar o ANTES, e não um "inverso" da operação, é o que torna o desfazer
-- confiável: não importa o que a operação fez nem em que ordem, voltar é
-- reescrever o que estava lá. Há poucos dias, nesta mesma base, uma rotina de
-- reparo quase empurrou 69 faturas corretas para o mês errado — foi o registro
-- do antes que permitiu conferir sem adivinhar.
CREATE TABLE IF NOT EXISTS organizador_acoes (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     integer NOT NULL,
  tipo        text    NOT NULL,
  resumo      text    NOT NULL,
  afetados    integer NOT NULL DEFAULT 0,
  antes       text    NOT NULL DEFAULT '[]',
  criado_em   text    DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  desfeito_em text
);

CREATE INDEX IF NOT EXISTS idx_org_acoes_user ON organizador_acoes (user_id, criado_em DESC);

ALTER TABLE organizador_acoes DROP CONSTRAINT IF EXISTS organizador_acoes_user_fk;
ALTER TABLE organizador_acoes ADD CONSTRAINT organizador_acoes_user_fk
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- ── Decisões adiadas e recusadas ────────────────────────────────────────────
-- "Depois" e "São coisas diferentes" precisam ser LEMBRADOS. Repetir a mesma
-- pergunta todo mês é como um app perde a confiança de quem usa; e é diferente
-- de "não perguntar mais", que vale para sempre. `ate` NULL = para sempre.
CREATE TABLE IF NOT EXISTS organizador_dispensas (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     integer NOT NULL,
  decisao_id  text    NOT NULL,
  motivo      text    NOT NULL DEFAULT 'adiada' CHECK(motivo IN ('adiada','recusada')),
  ate         text,
  criado_em   text    DEFAULT to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(user_id, decisao_id)
);

CREATE INDEX IF NOT EXISTS idx_org_dispensas_user ON organizador_dispensas (user_id);

ALTER TABLE organizador_dispensas DROP CONSTRAINT IF EXISTS organizador_dispensas_user_fk;
ALTER TABLE organizador_dispensas ADD CONSTRAINT organizador_dispensas_user_fk
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
